# Generated by Django 2.1.3 on 2018-11-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='番号')),
                ('en_word', models.CharField(max_length=200, verbose_name='英単語')),
                ('jp_word', models.CharField(max_length=200, verbose_name='日本語訳')),
            ],
            options={
                'verbose_name': 'テスト単語帳',
                'verbose_name_plural': 'テスト単語帳',
            },
        ),
    ]
