# Generated by Django 2.1.3 on 2018-12-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_target_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Target_1900',
        ),
    ]
